<?php

namespace App\Form;

use App\Entity\MarketSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MarketSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder// todo revoir les type et place holder...
            ->add('tag')
            ->add('sector')
            ->add('date')
            ->add('provider')
            ->add('market')
            ->add('affiday')
            ->add('affiweek')
            ->add('affimonth')
            ->add('affiyear')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MarketSearch::class,
            'method'=>'get',
            'csrf_protection'=>false
        ]);
    }
    public function getBlockPrefix()
    {
        return ""; // TODO: Change the autogenerated stub
    }
}
